# -*- coding: utf-8 -*-
"""Option data for BFSU WebLens.

The language and country/region options below keep Google's internal lr/cr
parameter values for URL generation, but the GUI displays only human-readable
names. Technical values such as lang_en and countryUS are intentionally hidden
from list labels in the release UI to avoid user-facing misunderstanding.
"""
from __future__ import annotations

APP_LANGS = [{'key': 'en', 'labels': {'en': 'English', 'zh_sim': '英语', 'zh_tra': '英語'}},
 {'key': 'zh_sim', 'labels': {'en': 'Simplified Chinese', 'zh_sim': '简体中文', 'zh_tra': '簡體中文'}},
 {'key': 'zh_tra', 'labels': {'en': 'Traditional Chinese', 'zh_sim': '繁体中文', 'zh_tra': '繁體中文'}}]

LANGUAGE_OPTIONS = [{'key': 'none',
  'lr': '',
  'code': '',
  'labels': {'en': 'No language restriction', 'zh_sim': '不限定语种', 'zh_tra': '不限定語種'}},
 {'key': 'af', 'lr': 'lang_af', 'code': 'af', 'labels': {'en': 'Afrikaans', 'zh_sim': '南非荷兰语', 'zh_tra': '南非荷蘭語'}},
 {'key': 'sq', 'lr': 'lang_sq', 'code': 'sq', 'labels': {'en': 'Albanian', 'zh_sim': '阿尔巴尼亚语', 'zh_tra': '阿爾巴尼亞語'}},
 {'key': 'sm', 'lr': 'lang_sm', 'code': 'sm', 'labels': {'en': 'Amharic', 'zh_sim': '阿姆哈拉语', 'zh_tra': '阿姆哈拉語'}},
 {'key': 'ar', 'lr': 'lang_ar', 'code': 'ar', 'labels': {'en': 'Arabic', 'zh_sim': '阿拉伯语', 'zh_tra': '阿拉伯語'}},
 {'key': 'az', 'lr': 'lang_az', 'code': 'az', 'labels': {'en': 'Azerbaijani', 'zh_sim': '阿塞拜疆语', 'zh_tra': '阿塞拜疆語'}},
 {'key': 'eu', 'lr': 'lang_eu', 'code': 'eu', 'labels': {'en': 'Basque', 'zh_sim': '巴斯克语', 'zh_tra': '巴斯克語'}},
 {'key': 'be', 'lr': 'lang_be', 'code': 'be', 'labels': {'en': 'Belarusian', 'zh_sim': '白俄罗斯语', 'zh_tra': '白俄羅斯語'}},
 {'key': 'bn', 'lr': 'lang_bn', 'code': 'bn', 'labels': {'en': 'Bengali', 'zh_sim': '孟加拉语', 'zh_tra': '孟加拉語'}},
 {'key': 'bh', 'lr': 'lang_bh', 'code': 'bh', 'labels': {'en': 'Bihari', 'zh_sim': '比哈里语', 'zh_tra': '比哈里語'}},
 {'key': 'bs', 'lr': 'lang_bs', 'code': 'bs', 'labels': {'en': 'Bosnian', 'zh_sim': '波斯尼亚语', 'zh_tra': '波斯尼亞語'}},
 {'key': 'bg', 'lr': 'lang_bg', 'code': 'bg', 'labels': {'en': 'Bulgarian', 'zh_sim': '保加利亚语', 'zh_tra': '保加利亞語'}},
 {'key': 'ca', 'lr': 'lang_ca', 'code': 'ca', 'labels': {'en': 'Catalan', 'zh_sim': '加泰罗尼亚语', 'zh_tra': '加泰羅尼亞語'}},
 {'key': 'zh-CN',
  'lr': 'lang_zh-CN',
  'code': 'zh-CN',
  'labels': {'en': 'Chinese Simplified', 'zh_sim': '中文简体', 'zh_tra': '中文簡體'}},
 {'key': 'zh-TW',
  'lr': 'lang_zh-TW',
  'code': 'zh-TW',
  'labels': {'en': 'Chinese Traditional', 'zh_sim': '中文繁体', 'zh_tra': '中文繁體'}},
 {'key': 'hr', 'lr': 'lang_hr', 'code': 'hr', 'labels': {'en': 'Croatian', 'zh_sim': '克罗地亚语', 'zh_tra': '克羅地亞語'}},
 {'key': 'cs', 'lr': 'lang_cs', 'code': 'cs', 'labels': {'en': 'Czech', 'zh_sim': '捷克语', 'zh_tra': '捷克語'}},
 {'key': 'da', 'lr': 'lang_da', 'code': 'da', 'labels': {'en': 'Danish', 'zh_sim': '丹麦语', 'zh_tra': '丹麥語'}},
 {'key': 'nl', 'lr': 'lang_nl', 'code': 'nl', 'labels': {'en': 'Dutch', 'zh_sim': '荷兰语', 'zh_tra': '荷蘭語'}},
 {'key': 'en', 'lr': 'lang_en', 'code': 'en', 'labels': {'en': 'English', 'zh_sim': '英语', 'zh_tra': '英語'}},
 {'key': 'eo', 'lr': 'lang_eo', 'code': 'eo', 'labels': {'en': 'Esperanto', 'zh_sim': '世界语', 'zh_tra': '世界語'}},
 {'key': 'et', 'lr': 'lang_et', 'code': 'et', 'labels': {'en': 'Estonian', 'zh_sim': '爱沙尼亚语', 'zh_tra': '爱沙尼亞語'}},
 {'key': 'fo', 'lr': 'lang_fo', 'code': 'fo', 'labels': {'en': 'Faroese', 'zh_sim': '法罗语', 'zh_tra': '法羅語'}},
 {'key': 'fi', 'lr': 'lang_fi', 'code': 'fi', 'labels': {'en': 'Finnish', 'zh_sim': '芬兰语', 'zh_tra': '芬蘭語'}},
 {'key': 'fr', 'lr': 'lang_fr', 'code': 'fr', 'labels': {'en': 'French', 'zh_sim': '法语', 'zh_tra': '法語'}},
 {'key': 'fy', 'lr': 'lang_fy', 'code': 'fy', 'labels': {'en': 'Frisian', 'zh_sim': '弗里斯兰语', 'zh_tra': '弗里斯蘭語'}},
 {'key': 'gl', 'lr': 'lang_gl', 'code': 'gl', 'labels': {'en': 'Galician', 'zh_sim': '加利西亚语', 'zh_tra': '加利西亞語'}},
 {'key': 'ka', 'lr': 'lang_ka', 'code': 'ka', 'labels': {'en': 'Georgian', 'zh_sim': '格鲁吉亚语', 'zh_tra': '格魯吉亞語'}},
 {'key': 'de', 'lr': 'lang_de', 'code': 'de', 'labels': {'en': 'German', 'zh_sim': '德语', 'zh_tra': '德語'}},
 {'key': 'el', 'lr': 'lang_el', 'code': 'el', 'labels': {'en': 'Greek', 'zh_sim': '希腊语', 'zh_tra': '希臘語'}},
 {'key': 'gu', 'lr': 'lang_gu', 'code': 'gu', 'labels': {'en': 'Gujarati', 'zh_sim': '古吉拉特语', 'zh_tra': '古吉拉特語'}},
 {'key': 'iw', 'lr': 'lang_iw', 'code': 'iw', 'labels': {'en': 'Hebrew', 'zh_sim': '希伯来语', 'zh_tra': '希伯来語'}},
 {'key': 'hi', 'lr': 'lang_hi', 'code': 'hi', 'labels': {'en': 'Hindi', 'zh_sim': '印地语', 'zh_tra': '印地語'}},
 {'key': 'hu', 'lr': 'lang_hu', 'code': 'hu', 'labels': {'en': 'Hungarian', 'zh_sim': '匈牙利语', 'zh_tra': '匈牙利語'}},
 {'key': 'is', 'lr': 'lang_is', 'code': 'is', 'labels': {'en': 'Icelandic', 'zh_sim': '冰岛语', 'zh_tra': '冰島語'}},
 {'key': 'id', 'lr': 'lang_id', 'code': 'id', 'labels': {'en': 'Indonesian', 'zh_sim': '印度尼西亚语', 'zh_tra': '印度尼西亞語'}},
 {'key': 'ia', 'lr': 'lang_ia', 'code': 'ia', 'labels': {'en': 'Interlingua', 'zh_sim': '国际语', 'zh_tra': '國际語'}},
 {'key': 'ga', 'lr': 'lang_ga', 'code': 'ga', 'labels': {'en': 'Irish', 'zh_sim': '爱尔兰语', 'zh_tra': '爱爾蘭語'}},
 {'key': 'it', 'lr': 'lang_it', 'code': 'it', 'labels': {'en': 'Italian', 'zh_sim': '意大利语', 'zh_tra': '意大利語'}},
 {'key': 'ja', 'lr': 'lang_ja', 'code': 'ja', 'labels': {'en': 'Japanese', 'zh_sim': '日语', 'zh_tra': '日語'}},
 {'key': 'jw', 'lr': 'lang_jw', 'code': 'jw', 'labels': {'en': 'Javanese', 'zh_sim': '爪哇语', 'zh_tra': '爪哇語'}},
 {'key': 'kn', 'lr': 'lang_kn', 'code': 'kn', 'labels': {'en': 'Kannada', 'zh_sim': '卡纳达语', 'zh_tra': '卡納達語'}},
 {'key': 'ko', 'lr': 'lang_ko', 'code': 'ko', 'labels': {'en': 'Korean', 'zh_sim': '韩语', 'zh_tra': '韓語'}},
 {'key': 'la', 'lr': 'lang_la', 'code': 'la', 'labels': {'en': 'Latin', 'zh_sim': '拉丁文', 'zh_tra': '拉丁文'}},
 {'key': 'lv', 'lr': 'lang_lv', 'code': 'lv', 'labels': {'en': 'Latvian', 'zh_sim': '拉脱维亚语', 'zh_tra': '拉脱維亞語'}},
 {'key': 'lt', 'lr': 'lang_lt', 'code': 'lt', 'labels': {'en': 'Lithuanian', 'zh_sim': '立陶宛语', 'zh_tra': '立陶宛語'}},
 {'key': 'mk', 'lr': 'lang_mk', 'code': 'mk', 'labels': {'en': 'Macedonian', 'zh_sim': '马其顿语', 'zh_tra': '馬其顿語'}},
 {'key': 'ms', 'lr': 'lang_ms', 'code': 'ms', 'labels': {'en': 'Malay', 'zh_sim': '马来语', 'zh_tra': '馬来語'}},
 {'key': 'ml', 'lr': 'lang_ml', 'code': 'ml', 'labels': {'en': 'Malayalam', 'zh_sim': '马来亚语', 'zh_tra': '馬来亞語'}},
 {'key': 'mt', 'lr': 'lang_mt', 'code': 'mt', 'labels': {'en': 'Maltese', 'zh_sim': '马耳他语', 'zh_tra': '馬耳他語'}},
 {'key': 'mr', 'lr': 'lang_mr', 'code': 'mr', 'labels': {'en': 'Marathi', 'zh_sim': '马拉地语', 'zh_tra': '馬拉地語'}},
 {'key': 'ne', 'lr': 'lang_ne', 'code': 'ne', 'labels': {'en': 'Nepali', 'zh_sim': '尼泊尔语', 'zh_tra': '尼泊爾語'}},
 {'key': 'no', 'lr': 'lang_no', 'code': 'no', 'labels': {'en': 'Norwegian', 'zh_sim': '挪威语', 'zh_tra': '挪威語'}},
 {'key': 'nn',
  'lr': 'lang_nn',
  'code': 'nn',
  'labels': {'en': 'Norwegian Nynorsk', 'zh_sim': '挪威语（尼诺斯克语）', 'zh_tra': '挪威語（尼诺斯克語）'}},
 {'key': 'oc', 'lr': 'lang_oc', 'code': 'oc', 'labels': {'en': 'Occitan', 'zh_sim': '奥克斯坦语', 'zh_tra': '奥克斯坦語'}},
 {'key': 'fa', 'lr': 'lang_fa', 'code': 'fa', 'labels': {'en': 'Persian', 'zh_sim': '波斯语', 'zh_tra': '波斯語'}},
 {'key': 'pl', 'lr': 'lang_pl', 'code': 'pl', 'labels': {'en': 'Polish', 'zh_sim': '波兰语', 'zh_tra': '波蘭語'}},
 {'key': 'pt-BR',
  'lr': 'lang_pt-BR',
  'code': 'pt-BR',
  'labels': {'en': 'Portuguese (Brazil)', 'zh_sim': '葡萄牙语（巴西）', 'zh_tra': '葡萄牙語（巴西）'}},
 {'key': 'pt-PT',
  'lr': 'lang_pt-PT',
  'code': 'pt-PT',
  'labels': {'en': 'Portuguese (Portugal)', 'zh_sim': '葡萄牙语（葡萄牙）', 'zh_tra': '葡萄牙語（葡萄牙）'}},
 {'key': 'pa', 'lr': 'lang_pa', 'code': 'pa', 'labels': {'en': 'Punjabi', 'zh_sim': '旁遮普语', 'zh_tra': '旁遮普語'}},
 {'key': 'ro', 'lr': 'lang_ro', 'code': 'ro', 'labels': {'en': 'Romanian', 'zh_sim': '罗马尼亚语', 'zh_tra': '羅馬尼亞語'}},
 {'key': 'ru', 'lr': 'lang_ru', 'code': 'ru', 'labels': {'en': 'Russian', 'zh_sim': '俄语', 'zh_tra': '俄語'}},
 {'key': 'gd',
  'lr': 'lang_gd',
  'code': 'gd',
  'labels': {'en': 'Scottish Gaelic', 'zh_sim': '苏格兰盖尔语', 'zh_tra': '蘇格蘭盖爾語'}},
 {'key': 'sr', 'lr': 'lang_sr', 'code': 'sr', 'labels': {'en': 'Serbian', 'zh_sim': '塞尔维亚语', 'zh_tra': '塞爾維亞語'}},
 {'key': 'si', 'lr': 'lang_si', 'code': 'si', 'labels': {'en': 'Sinhala', 'zh_sim': '僧伽罗语', 'zh_tra': '僧伽羅語'}},
 {'key': 'sk', 'lr': 'lang_sk', 'code': 'sk', 'labels': {'en': 'Slovak', 'zh_sim': '斯洛伐克语', 'zh_tra': '斯洛伐克語'}},
 {'key': 'sl', 'lr': 'lang_sl', 'code': 'sl', 'labels': {'en': 'Slovenian', 'zh_sim': '斯洛文尼亚语', 'zh_tra': '斯洛文尼亞語'}},
 {'key': 'es', 'lr': 'lang_es', 'code': 'es', 'labels': {'en': 'Spanish', 'zh_sim': '西班牙语', 'zh_tra': '西班牙語'}},
 {'key': 'su', 'lr': 'lang_su', 'code': 'su', 'labels': {'en': 'Sundanese', 'zh_sim': '苏丹语', 'zh_tra': '蘇丹語'}},
 {'key': 'sw', 'lr': 'lang_sw', 'code': 'sw', 'labels': {'en': 'Swahili', 'zh_sim': '斯瓦希里语', 'zh_tra': '斯瓦希里語'}},
 {'key': 'sv', 'lr': 'lang_sv', 'code': 'sv', 'labels': {'en': 'Swedish', 'zh_sim': '瑞典语', 'zh_tra': '瑞典語'}},
 {'key': 'tl', 'lr': 'lang_tl', 'code': 'tl', 'labels': {'en': 'Tagalog', 'zh_sim': '塔加路文', 'zh_tra': '塔加路文'}},
 {'key': 'ta', 'lr': 'lang_ta', 'code': 'ta', 'labels': {'en': 'Tamil', 'zh_sim': '泰米尔文', 'zh_tra': '泰米爾文'}},
 {'key': 'te', 'lr': 'lang_te', 'code': 'te', 'labels': {'en': 'Telugu', 'zh_sim': '泰卢固语', 'zh_tra': '泰盧固語'}},
 {'key': 'th', 'lr': 'lang_th', 'code': 'th', 'labels': {'en': 'Thai', 'zh_sim': '泰语', 'zh_tra': '泰語'}},
 {'key': 'ti', 'lr': 'lang_ti', 'code': 'ti', 'labels': {'en': 'Tigrinya', 'zh_sim': '提格里尼亚语', 'zh_tra': '提格里尼亞語'}},
 {'key': 'tr', 'lr': 'lang_tr', 'code': 'tr', 'labels': {'en': 'Turkish', 'zh_sim': '土耳其语', 'zh_tra': '土耳其語'}},
 {'key': 'uk', 'lr': 'lang_uk', 'code': 'uk', 'labels': {'en': 'Ukrainian', 'zh_sim': '乌克兰语', 'zh_tra': '烏克蘭語'}},
 {'key': 'ur', 'lr': 'lang_ur', 'code': 'ur', 'labels': {'en': 'Urdu', 'zh_sim': '乌尔都语', 'zh_tra': '烏爾都語'}},
 {'key': 'uz', 'lr': 'lang_uz', 'code': 'uz', 'labels': {'en': 'Uzbek', 'zh_sim': '乌兹别克语', 'zh_tra': '烏兹别克語'}},
 {'key': 'vi', 'lr': 'lang_vi', 'code': 'vi', 'labels': {'en': 'Vietnamese', 'zh_sim': '越南语', 'zh_tra': '越南語'}},
 {'key': 'cy', 'lr': 'lang_cy', 'code': 'cy', 'labels': {'en': 'Welsh', 'zh_sim': '威尔士语', 'zh_tra': '威爾士語'}},
 {'key': 'xh', 'lr': 'lang_xh', 'code': 'xh', 'labels': {'en': 'Xhosa', 'zh_sim': '科萨语', 'zh_tra': '科薩語'}},
 {'key': 'zu', 'lr': 'lang_zu', 'code': 'zu', 'labels': {'en': 'Zulu', 'zh_sim': '祖鲁语', 'zh_tra': '祖魯語'}}]

COUNTRY_OPTIONS = [{'key': 'none',
  'cr': '',
  'code': '',
  'labels': {'en': 'No country/region restriction', 'zh_sim': '不限定国家/地区', 'zh_tra': '不限定國家/地區'}},
 {'key': 'AF', 'cr': 'countryAF', 'code': 'AF', 'labels': {'en': 'Afghanistan', 'zh_sim': '阿富汗', 'zh_tra': '阿富汗'}},
 {'key': 'AL', 'cr': 'countryAL', 'code': 'AL', 'labels': {'en': 'Albania', 'zh_sim': '阿尔巴尼亚', 'zh_tra': '阿爾巴尼亞'}},
 {'key': 'DZ', 'cr': 'countryDZ', 'code': 'DZ', 'labels': {'en': 'Algeria', 'zh_sim': '阿尔及利亚', 'zh_tra': '阿爾及利亞'}},
 {'key': 'AS',
  'cr': 'countryAS',
  'code': 'AS',
  'labels': {'en': 'American Samoa', 'zh_sim': '美属萨摩亚', 'zh_tra': '美属薩摩亞'}},
 {'key': 'AD', 'cr': 'countryAD', 'code': 'AD', 'labels': {'en': 'Andorra', 'zh_sim': '安道尔', 'zh_tra': '安道爾'}},
 {'key': 'AO', 'cr': 'countryAO', 'code': 'AO', 'labels': {'en': 'Angola', 'zh_sim': '安哥拉', 'zh_tra': '安哥拉'}},
 {'key': 'AI', 'cr': 'countryAI', 'code': 'AI', 'labels': {'en': 'Anguilla', 'zh_sim': '安圭拉', 'zh_tra': '安圭拉'}},
 {'key': 'AQ', 'cr': 'countryAQ', 'code': 'AQ', 'labels': {'en': 'Antarctica', 'zh_sim': '南极洲', 'zh_tra': '南极洲'}},
 {'key': 'AG',
  'cr': 'countryAG',
  'code': 'AG',
  'labels': {'en': 'Antigua and Barbuda', 'zh_sim': '安提瓜和巴布达', 'zh_tra': '安提瓜和巴布達'}},
 {'key': 'AR', 'cr': 'countryAR', 'code': 'AR', 'labels': {'en': 'Argentina', 'zh_sim': '阿根廷', 'zh_tra': '阿根廷'}},
 {'key': 'AM', 'cr': 'countryAM', 'code': 'AM', 'labels': {'en': 'Armenia', 'zh_sim': '亚美尼亚', 'zh_tra': '亞美尼亞'}},
 {'key': 'AW', 'cr': 'countryAW', 'code': 'AW', 'labels': {'en': 'Aruba', 'zh_sim': '阿鲁巴', 'zh_tra': '阿魯巴'}},
 {'key': 'AU', 'cr': 'countryAU', 'code': 'AU', 'labels': {'en': 'Australia', 'zh_sim': '澳大利亚', 'zh_tra': '澳大利亞'}},
 {'key': 'AT', 'cr': 'countryAT', 'code': 'AT', 'labels': {'en': 'Austria', 'zh_sim': '奥地利', 'zh_tra': '奥地利'}},
 {'key': 'AZ', 'cr': 'countryAZ', 'code': 'AZ', 'labels': {'en': 'Azerbaijan', 'zh_sim': '阿塞拜疆', 'zh_tra': '阿塞拜疆'}},
 {'key': 'BS', 'cr': 'countryBS', 'code': 'BS', 'labels': {'en': 'Bahamas', 'zh_sim': '巴哈马', 'zh_tra': '巴哈馬'}},
 {'key': 'BH', 'cr': 'countryBH', 'code': 'BH', 'labels': {'en': 'Bahrain', 'zh_sim': '巴林', 'zh_tra': '巴林'}},
 {'key': 'BD', 'cr': 'countryBD', 'code': 'BD', 'labels': {'en': 'Bangladesh', 'zh_sim': '孟加拉国', 'zh_tra': '孟加拉國'}},
 {'key': 'BB', 'cr': 'countryBB', 'code': 'BB', 'labels': {'en': 'Barbados', 'zh_sim': '巴巴多斯', 'zh_tra': '巴巴多斯'}},
 {'key': 'BY', 'cr': 'countryBY', 'code': 'BY', 'labels': {'en': 'Belarus', 'zh_sim': '白俄罗斯', 'zh_tra': '白俄羅斯'}},
 {'key': 'BE', 'cr': 'countryBE', 'code': 'BE', 'labels': {'en': 'Belgium', 'zh_sim': '比利时', 'zh_tra': '比利时'}},
 {'key': 'BZ', 'cr': 'countryBZ', 'code': 'BZ', 'labels': {'en': 'Belize', 'zh_sim': '伯利兹', 'zh_tra': '伯利兹'}},
 {'key': 'BJ', 'cr': 'countryBJ', 'code': 'BJ', 'labels': {'en': 'Benin', 'zh_sim': '贝宁', 'zh_tra': '貝宁'}},
 {'key': 'BM', 'cr': 'countryBM', 'code': 'BM', 'labels': {'en': 'Bermuda', 'zh_sim': '百慕大', 'zh_tra': '百慕大'}},
 {'key': 'BT', 'cr': 'countryBT', 'code': 'BT', 'labels': {'en': 'Bhutan', 'zh_sim': '不丹', 'zh_tra': '不丹'}},
 {'key': 'BO',
  'cr': 'countryBO',
  'code': 'BO',
  'labels': {'en': 'Bolivia, Plurinational State of', 'zh_sim': '玻利维亚', 'zh_tra': '玻利維亞'}},
 {'key': 'BA',
  'cr': 'countryBA',
  'code': 'BA',
  'labels': {'en': 'Bosnia and Herzegovina', 'zh_sim': '波斯尼亚和黑塞哥维那', 'zh_tra': '波斯尼亞和黑塞哥維那'}},
 {'key': 'BW', 'cr': 'countryBW', 'code': 'BW', 'labels': {'en': 'Botswana', 'zh_sim': '博茨瓦纳', 'zh_tra': '博茨瓦納'}},
 {'key': 'BV', 'cr': 'countryBV', 'code': 'BV', 'labels': {'en': 'Bouvet Island', 'zh_sim': '布韦岛', 'zh_tra': '布韦島'}},
 {'key': 'BR', 'cr': 'countryBR', 'code': 'BR', 'labels': {'en': 'Brazil', 'zh_sim': '巴西', 'zh_tra': '巴西'}},
 {'key': 'IO',
  'cr': 'countryIO',
  'code': 'IO',
  'labels': {'en': 'British Indian Ocean Territory', 'zh_sim': '英属印度洋领地', 'zh_tra': '英属印度洋领地'}},
 {'key': 'BN',
  'cr': 'countryBN',
  'code': 'BN',
  'labels': {'en': 'Brunei Darussalam', 'zh_sim': '文莱达鲁萨兰国', 'zh_tra': '文萊達魯薩蘭國'}},
 {'key': 'BG', 'cr': 'countryBG', 'code': 'BG', 'labels': {'en': 'Bulgaria', 'zh_sim': '保加利亚', 'zh_tra': '保加利亞'}},
 {'key': 'BF', 'cr': 'countryBF', 'code': 'BF', 'labels': {'en': 'Burkina Faso', 'zh_sim': '布基纳法索', 'zh_tra': '布基納法索'}},
 {'key': 'BI', 'cr': 'countryBI', 'code': 'BI', 'labels': {'en': 'Burundi', 'zh_sim': '布隆迪', 'zh_tra': '布隆迪'}},
 {'key': 'KH', 'cr': 'countryKH', 'code': 'KH', 'labels': {'en': 'Cambodia', 'zh_sim': '柬埔寨', 'zh_tra': '柬埔寨'}},
 {'key': 'CM', 'cr': 'countryCM', 'code': 'CM', 'labels': {'en': 'Cameroon', 'zh_sim': '喀麦隆', 'zh_tra': '喀麥隆'}},
 {'key': 'CA', 'cr': 'countryCA', 'code': 'CA', 'labels': {'en': 'Canada', 'zh_sim': '加拿大', 'zh_tra': '加拿大'}},
 {'key': 'CV', 'cr': 'countryCV', 'code': 'CV', 'labels': {'en': 'Cabo Verde', 'zh_sim': '佛得角', 'zh_tra': '佛得角'}},
 {'key': 'KY', 'cr': 'countryKY', 'code': 'KY', 'labels': {'en': 'Cayman Islands', 'zh_sim': '开曼群岛', 'zh_tra': '开曼群島'}},
 {'key': 'CF',
  'cr': 'countryCF',
  'code': 'CF',
  'labels': {'en': 'Central African Republic', 'zh_sim': '中非共和国', 'zh_tra': '中非共和國'}},
 {'key': 'TD', 'cr': 'countryTD', 'code': 'TD', 'labels': {'en': 'Chad', 'zh_sim': '乍得', 'zh_tra': '乍得'}},
 {'key': 'CL', 'cr': 'countryCL', 'code': 'CL', 'labels': {'en': 'Chile', 'zh_sim': '智利', 'zh_tra': '智利'}},
 {'key': 'CN', 'cr': 'countryCN', 'code': 'CN', 'labels': {'en': 'China', 'zh_sim': '中国', 'zh_tra': '中國'}},
 {'key': 'CX', 'cr': 'countryCX', 'code': 'CX', 'labels': {'en': 'Christmas Island', 'zh_sim': '圣诞岛', 'zh_tra': '聖诞島'}},
 {'key': 'CC',
  'cr': 'countryCC',
  'code': 'CC',
  'labels': {'en': 'Cocos (Keeling) Islands', 'zh_sim': '科科斯（基林）群岛', 'zh_tra': '科科斯（基林）群島'}},
 {'key': 'CO', 'cr': 'countryCO', 'code': 'CO', 'labels': {'en': 'Colombia', 'zh_sim': '哥伦比亚', 'zh_tra': '哥倫比亞'}},
 {'key': 'KM', 'cr': 'countryKM', 'code': 'KM', 'labels': {'en': 'Comoros', 'zh_sim': '科摩罗', 'zh_tra': '科摩羅'}},
 {'key': 'CG', 'cr': 'countryCG', 'code': 'CG', 'labels': {'en': 'Congo', 'zh_sim': '刚果', 'zh_tra': '刚果'}},
 {'key': 'CD',
  'cr': 'countryCD',
  'code': 'CD',
  'labels': {'en': 'Democratic Republic of the Congo', 'zh_sim': '刚果民主共和国', 'zh_tra': '刚果民主共和國'}},
 {'key': 'CK', 'cr': 'countryCK', 'code': 'CK', 'labels': {'en': 'Cook Islands', 'zh_sim': '库克群岛', 'zh_tra': '庫克群島'}},
 {'key': 'CR', 'cr': 'countryCR', 'code': 'CR', 'labels': {'en': 'Costa Rica', 'zh_sim': '哥斯达黎加', 'zh_tra': '哥斯達黎加'}},
 {'key': 'CI', 'cr': 'countryCI', 'code': 'CI', 'labels': {'en': "Côte d'Ivoire", 'zh_sim': '科特迪瓦', 'zh_tra': '科特迪瓦'}},
 {'key': 'HR',
  'cr': 'countryHR',
  'code': 'HR',
  'labels': {'en': 'Croatia', 'zh_sim': '克罗地亚 (Hrvatska)', 'zh_tra': '克羅地亞 (Hrvatska)'}},
 {'key': 'CU', 'cr': 'countryCU', 'code': 'CU', 'labels': {'en': 'Cuba', 'zh_sim': '古巴', 'zh_tra': '古巴'}},
 {'key': 'CY', 'cr': 'countryCY', 'code': 'CY', 'labels': {'en': 'Cyprus', 'zh_sim': '塞浦路斯', 'zh_tra': '塞浦路斯'}},
 {'key': 'CZ', 'cr': 'countryCZ', 'code': 'CZ', 'labels': {'en': 'Czechia', 'zh_sim': '捷克', 'zh_tra': '捷克'}},
 {'key': 'DK', 'cr': 'countryDK', 'code': 'DK', 'labels': {'en': 'Denmark', 'zh_sim': '丹麦', 'zh_tra': '丹麥'}},
 {'key': 'DJ', 'cr': 'countryDJ', 'code': 'DJ', 'labels': {'en': 'Djibouti', 'zh_sim': '吉布提', 'zh_tra': '吉布提'}},
 {'key': 'DM', 'cr': 'countryDM', 'code': 'DM', 'labels': {'en': 'Dominica', 'zh_sim': '多米尼加', 'zh_tra': '多米尼加'}},
 {'key': 'DO',
  'cr': 'countryDO',
  'code': 'DO',
  'labels': {'en': 'Dominican Republic', 'zh_sim': '多米尼加共和国', 'zh_tra': '多米尼加共和國'}},
 {'key': 'TP', 'cr': 'countryTP', 'code': 'TP', 'labels': {'en': 'East Timor', 'zh_sim': '东帝汶', 'zh_tra': '東帝汶'}},
 {'key': 'EC', 'cr': 'countryEC', 'code': 'EC', 'labels': {'en': 'Ecuador', 'zh_sim': '厄瓜多尔', 'zh_tra': '厄瓜多爾'}},
 {'key': 'EG', 'cr': 'countryEG', 'code': 'EG', 'labels': {'en': 'Egypt', 'zh_sim': '埃及', 'zh_tra': '埃及'}},
 {'key': 'SV', 'cr': 'countrySV', 'code': 'SV', 'labels': {'en': 'El Salvador', 'zh_sim': '萨尔瓦多', 'zh_tra': '薩爾瓦多'}},
 {'key': 'GQ',
  'cr': 'countryGQ',
  'code': 'GQ',
  'labels': {'en': 'Equatorial Guinea', 'zh_sim': '赤道几内亚', 'zh_tra': '赤道几内亞'}},
 {'key': 'ER', 'cr': 'countryER', 'code': 'ER', 'labels': {'en': 'Eritrea', 'zh_sim': '厄立特里亚', 'zh_tra': '厄立特里亞'}},
 {'key': 'EE', 'cr': 'countryEE', 'code': 'EE', 'labels': {'en': 'Estonia', 'zh_sim': '爱沙尼亚', 'zh_tra': '爱沙尼亞'}},
 {'key': 'ET', 'cr': 'countryET', 'code': 'ET', 'labels': {'en': 'Ethiopia', 'zh_sim': '埃塞俄比亚', 'zh_tra': '埃塞俄比亞'}},
 {'key': 'EU', 'cr': 'countryEU', 'code': 'EU', 'labels': {'en': 'European Union', 'zh_sim': '欧盟', 'zh_tra': '欧盟'}},
 {'key': 'FK',
  'cr': 'countryFK',
  'code': 'FK',
  'labels': {'en': 'Falkland Islands (Malvinas)', 'zh_sim': '福克兰群岛（马尔维纳斯群岛）', 'zh_tra': '福克蘭群島（馬爾維納斯群島）'}},
 {'key': 'FO', 'cr': 'countryFO', 'code': 'FO', 'labels': {'en': 'Faroe Islands', 'zh_sim': '法罗群岛', 'zh_tra': '法羅群島'}},
 {'key': 'FJ', 'cr': 'countryFJ', 'code': 'FJ', 'labels': {'en': 'Fiji', 'zh_sim': '斐济', 'zh_tra': '斐济'}},
 {'key': 'FI', 'cr': 'countryFI', 'code': 'FI', 'labels': {'en': 'Finland', 'zh_sim': '芬兰', 'zh_tra': '芬蘭'}},
 {'key': 'FR', 'cr': 'countryFR', 'code': 'FR', 'labels': {'en': 'France', 'zh_sim': '法国', 'zh_tra': '法國'}},
 {'key': 'FX',
  'cr': 'countryFX',
  'code': 'FX',
  'labels': {'en': 'Metropolitan France', 'zh_sim': '法国本土', 'zh_tra': '法國本土'}},
 {'key': 'GF',
  'cr': 'countryGF',
  'code': 'GF',
  'labels': {'en': 'French Guiana', 'zh_sim': '法属圭亚那', 'zh_tra': '法属圭亞那'}},
 {'key': 'PF',
  'cr': 'countryPF',
  'code': 'PF',
  'labels': {'en': 'French Polynesia', 'zh_sim': '法属波利尼西亚', 'zh_tra': '法属波利尼西亞'}},
 {'key': 'TF',
  'cr': 'countryTF',
  'code': 'TF',
  'labels': {'en': 'French Southern Territories', 'zh_sim': '法属南部领地', 'zh_tra': '法属南部领地'}},
 {'key': 'GA', 'cr': 'countryGA', 'code': 'GA', 'labels': {'en': 'Gabon', 'zh_sim': '加蓬', 'zh_tra': '加蓬'}},
 {'key': 'GM', 'cr': 'countryGM', 'code': 'GM', 'labels': {'en': 'Gambia', 'zh_sim': '冈比亚', 'zh_tra': '岡比亞'}},
 {'key': 'GE', 'cr': 'countryGE', 'code': 'GE', 'labels': {'en': 'Georgia', 'zh_sim': '格鲁吉亚', 'zh_tra': '格魯吉亞'}},
 {'key': 'DE', 'cr': 'countryDE', 'code': 'DE', 'labels': {'en': 'Germany', 'zh_sim': '德国', 'zh_tra': '德國'}},
 {'key': 'GH', 'cr': 'countryGH', 'code': 'GH', 'labels': {'en': 'Ghana', 'zh_sim': '加纳', 'zh_tra': '加納'}},
 {'key': 'GI', 'cr': 'countryGI', 'code': 'GI', 'labels': {'en': 'Gibraltar', 'zh_sim': '直布罗陀', 'zh_tra': '直布羅陀'}},
 {'key': 'GR', 'cr': 'countryGR', 'code': 'GR', 'labels': {'en': 'Greece', 'zh_sim': '希腊', 'zh_tra': '希臘'}},
 {'key': 'GL', 'cr': 'countryGL', 'code': 'GL', 'labels': {'en': 'Greenland', 'zh_sim': '格陵兰', 'zh_tra': '格陵蘭'}},
 {'key': 'GD', 'cr': 'countryGD', 'code': 'GD', 'labels': {'en': 'Grenada', 'zh_sim': '格林纳达', 'zh_tra': '格林納達'}},
 {'key': 'GP', 'cr': 'countryGP', 'code': 'GP', 'labels': {'en': 'Guadeloupe', 'zh_sim': '瓜德罗普', 'zh_tra': '瓜德羅普'}},
 {'key': 'GU', 'cr': 'countryGU', 'code': 'GU', 'labels': {'en': 'Guam', 'zh_sim': '关岛', 'zh_tra': '关島'}},
 {'key': 'GT', 'cr': 'countryGT', 'code': 'GT', 'labels': {'en': 'Guatemala', 'zh_sim': '危地马拉', 'zh_tra': '危地馬拉'}},
 {'key': 'GN', 'cr': 'countryGN', 'code': 'GN', 'labels': {'en': 'Guinea', 'zh_sim': '几内亚', 'zh_tra': '几内亞'}},
 {'key': 'GW',
  'cr': 'countryGW',
  'code': 'GW',
  'labels': {'en': 'Guinea-Bissau', 'zh_sim': '几内亚比绍', 'zh_tra': '几内亞比绍'}},
 {'key': 'GY', 'cr': 'countryGY', 'code': 'GY', 'labels': {'en': 'Guyana', 'zh_sim': '圭亚那', 'zh_tra': '圭亞那'}},
 {'key': 'HT', 'cr': 'countryHT', 'code': 'HT', 'labels': {'en': 'Haiti', 'zh_sim': '海地', 'zh_tra': '海地'}},
 {'key': 'HM',
  'cr': 'countryHM',
  'code': 'HM',
  'labels': {'en': 'Heard Island and McDonald Islands', 'zh_sim': '赫德岛和麦克唐纳群岛', 'zh_tra': '赫德島和麥克唐納群島'}},
 {'key': 'VA',
  'cr': 'countryVA',
  'code': 'VA',
  'labels': {'en': 'Holy See (Vatican City State)', 'zh_sim': '梵蒂冈（梵蒂冈城）', 'zh_tra': '梵蒂岡（梵蒂岡城）'}},
 {'key': 'HN', 'cr': 'countryHN', 'code': 'HN', 'labels': {'en': 'Honduras', 'zh_sim': '洪都拉斯', 'zh_tra': '洪都拉斯'}},
 {'key': 'HK',
  'cr': 'countryHK',
  'code': 'HK',
  'labels': {'en': 'China Hong Kong Special Administrative Region', 'zh_sim': '中国香港行政特区', 'zh_tra': '中國香港行政特區'}},
 {'key': 'HU', 'cr': 'countryHU', 'code': 'HU', 'labels': {'en': 'Hungary', 'zh_sim': '匈牙利', 'zh_tra': '匈牙利'}},
 {'key': 'IS', 'cr': 'countryIS', 'code': 'IS', 'labels': {'en': 'Iceland', 'zh_sim': '冰岛', 'zh_tra': '冰島'}},
 {'key': 'IN', 'cr': 'countryIN', 'code': 'IN', 'labels': {'en': 'India', 'zh_sim': '印度', 'zh_tra': '印度'}},
 {'key': 'ID', 'cr': 'countryID', 'code': 'ID', 'labels': {'en': 'Indonesia', 'zh_sim': '印度尼西亚', 'zh_tra': '印度尼西亞'}},
 {'key': 'IR', 'cr': 'countryIR', 'code': 'IR', 'labels': {'en': 'Iran', 'zh_sim': '伊朗伊斯兰共和国', 'zh_tra': '伊朗伊斯蘭共和國'}},
 {'key': 'IQ', 'cr': 'countryIQ', 'code': 'IQ', 'labels': {'en': 'Iraq', 'zh_sim': '伊拉克', 'zh_tra': '伊拉克'}},
 {'key': 'IE', 'cr': 'countryIE', 'code': 'IE', 'labels': {'en': 'Ireland', 'zh_sim': '爱尔兰', 'zh_tra': '爱爾蘭'}},
 {'key': 'IL', 'cr': 'countryIL', 'code': 'IL', 'labels': {'en': 'Israel', 'zh_sim': '以色列', 'zh_tra': '以色列'}},
 {'key': 'IT', 'cr': 'countryIT', 'code': 'IT', 'labels': {'en': 'Italy', 'zh_sim': '意大利', 'zh_tra': '意大利'}},
 {'key': 'JM', 'cr': 'countryJM', 'code': 'JM', 'labels': {'en': 'Jamaica', 'zh_sim': '牙买加', 'zh_tra': '牙买加'}},
 {'key': 'JP', 'cr': 'countryJP', 'code': 'JP', 'labels': {'en': 'Japan', 'zh_sim': '日本', 'zh_tra': '日本'}},
 {'key': 'JO', 'cr': 'countryJO', 'code': 'JO', 'labels': {'en': 'Jordan', 'zh_sim': '约旦', 'zh_tra': '約旦'}},
 {'key': 'KZ', 'cr': 'countryKZ', 'code': 'KZ', 'labels': {'en': 'Kazakhstan', 'zh_sim': '哈萨克斯坦', 'zh_tra': '哈薩克斯坦'}},
 {'key': 'KE', 'cr': 'countryKE', 'code': 'KE', 'labels': {'en': 'Kenya', 'zh_sim': '肯尼亚', 'zh_tra': '肯尼亞'}},
 {'key': 'KI', 'cr': 'countryKI', 'code': 'KI', 'labels': {'en': 'Kiribati', 'zh_sim': '基里巴斯', 'zh_tra': '基里巴斯'}},
 {'key': 'KP',
  'cr': 'countryKP',
  'code': 'KP',
  'labels': {'en': 'North Korea', 'zh_sim': '朝鲜人民民主共和国', 'zh_tra': '朝鲜人民民主共和國'}},
 {'key': 'KR', 'cr': 'countryKR', 'code': 'KR', 'labels': {'en': 'South Korea', 'zh_sim': '韩国', 'zh_tra': '韓國'}},
 {'key': 'KW', 'cr': 'countryKW', 'code': 'KW', 'labels': {'en': 'Kuwait', 'zh_sim': '科威特', 'zh_tra': '科威特'}},
 {'key': 'KG', 'cr': 'countryKG', 'code': 'KG', 'labels': {'en': 'Kyrgyzstan', 'zh_sim': '吉尔吉斯斯坦', 'zh_tra': '吉爾吉斯斯坦'}},
 {'key': 'LA', 'cr': 'countryLA', 'code': 'LA', 'labels': {'en': 'Laos', 'zh_sim': '老挝人民民主共和国', 'zh_tra': '老撾人民民主共和國'}},
 {'key': 'LV', 'cr': 'countryLV', 'code': 'LV', 'labels': {'en': 'Latvia', 'zh_sim': '拉脱维亚', 'zh_tra': '拉脱維亞'}},
 {'key': 'LB', 'cr': 'countryLB', 'code': 'LB', 'labels': {'en': 'Lebanon', 'zh_sim': '黎巴嫩', 'zh_tra': '黎巴嫩'}},
 {'key': 'LS', 'cr': 'countryLS', 'code': 'LS', 'labels': {'en': 'Lesotho', 'zh_sim': '莱索托', 'zh_tra': '萊索托'}},
 {'key': 'LR', 'cr': 'countryLR', 'code': 'LR', 'labels': {'en': 'Liberia', 'zh_sim': '利比里亚', 'zh_tra': '利比里亞'}},
 {'key': 'LY', 'cr': 'countryLY', 'code': 'LY', 'labels': {'en': 'Libya', 'zh_sim': '利比亚', 'zh_tra': '利比亞'}},
 {'key': 'LI',
  'cr': 'countryLI',
  'code': 'LI',
  'labels': {'en': 'Liechtenstein', 'zh_sim': '列支敦士登', 'zh_tra': '列支敦士登'}},
 {'key': 'LT', 'cr': 'countryLT', 'code': 'LT', 'labels': {'en': 'Lithuania', 'zh_sim': '立陶宛', 'zh_tra': '立陶宛'}},
 {'key': 'LU', 'cr': 'countryLU', 'code': 'LU', 'labels': {'en': 'Luxembourg', 'zh_sim': '卢森堡', 'zh_tra': '盧森堡'}},
 {'key': 'MO',
  'cr': 'countryMO',
  'code': 'MO',
  'labels': {'en': 'China Macao Special Administrative Region', 'zh_sim': '中国澳门行政特区', 'zh_tra': '中國澳門行政特區'}},
 {'key': 'MK',
  'cr': 'countryMK',
  'code': 'MK',
  'labels': {'en': 'North Macedonia', 'zh_sim': '马其顿（前南萨尔夫共和国）', 'zh_tra': '馬其顿（前南薩爾夫共和國）'}},
 {'key': 'MG', 'cr': 'countryMG', 'code': 'MG', 'labels': {'en': 'Madagascar', 'zh_sim': '马达加斯加', 'zh_tra': '馬達加斯加'}},
 {'key': 'MW', 'cr': 'countryMW', 'code': 'MW', 'labels': {'en': 'Malawi', 'zh_sim': '马拉维', 'zh_tra': '馬拉維'}},
 {'key': 'MY', 'cr': 'countryMY', 'code': 'MY', 'labels': {'en': 'Malaysia', 'zh_sim': '马来西亚', 'zh_tra': '馬来西亞'}},
 {'key': 'MV', 'cr': 'countryMV', 'code': 'MV', 'labels': {'en': 'Maldives', 'zh_sim': '马尔代夫', 'zh_tra': '馬爾代夫'}},
 {'key': 'ML', 'cr': 'countryML', 'code': 'ML', 'labels': {'en': 'Mali', 'zh_sim': '马里', 'zh_tra': '馬里'}},
 {'key': 'MT', 'cr': 'countryMT', 'code': 'MT', 'labels': {'en': 'Malta', 'zh_sim': '马耳他', 'zh_tra': '馬耳他'}},
 {'key': 'MH',
  'cr': 'countryMH',
  'code': 'MH',
  'labels': {'en': 'Marshall Islands', 'zh_sim': '马绍尔群岛', 'zh_tra': '馬绍爾群島'}},
 {'key': 'MQ', 'cr': 'countryMQ', 'code': 'MQ', 'labels': {'en': 'Martinique', 'zh_sim': '马提尼克', 'zh_tra': '馬提尼克'}},
 {'key': 'MR', 'cr': 'countryMR', 'code': 'MR', 'labels': {'en': 'Mauritania', 'zh_sim': '毛里塔尼亚', 'zh_tra': '毛里塔尼亞'}},
 {'key': 'MU', 'cr': 'countryMU', 'code': 'MU', 'labels': {'en': 'Mauritius', 'zh_sim': '毛里求斯', 'zh_tra': '毛里求斯'}},
 {'key': 'YT', 'cr': 'countryYT', 'code': 'YT', 'labels': {'en': 'Mayotte', 'zh_sim': '马约特岛', 'zh_tra': '馬約特島'}},
 {'key': 'MX', 'cr': 'countryMX', 'code': 'MX', 'labels': {'en': 'Mexico', 'zh_sim': '墨西哥', 'zh_tra': '墨西哥'}},
 {'key': 'FM',
  'cr': 'countryFM',
  'code': 'FM',
  'labels': {'en': 'Micronesia, Federated States of', 'zh_sim': '密克罗尼西亚联邦', 'zh_tra': '密克羅尼西亞聯邦'}},
 {'key': 'MD',
  'cr': 'countryMD',
  'code': 'MD',
  'labels': {'en': 'Moldova, Republic of', 'zh_sim': '摩尔多瓦共和国', 'zh_tra': '摩爾多瓦共和國'}},
 {'key': 'MC', 'cr': 'countryMC', 'code': 'MC', 'labels': {'en': 'Monaco', 'zh_sim': '摩纳哥', 'zh_tra': '摩納哥'}},
 {'key': 'MN', 'cr': 'countryMN', 'code': 'MN', 'labels': {'en': 'Mongolia', 'zh_sim': '蒙古', 'zh_tra': '蒙古'}},
 {'key': 'MS', 'cr': 'countryMS', 'code': 'MS', 'labels': {'en': 'Montserrat', 'zh_sim': '蒙塞拉特岛', 'zh_tra': '蒙塞拉特島'}},
 {'key': 'MA', 'cr': 'countryMA', 'code': 'MA', 'labels': {'en': 'Morocco', 'zh_sim': '摩洛哥', 'zh_tra': '摩洛哥'}},
 {'key': 'MZ', 'cr': 'countryMZ', 'code': 'MZ', 'labels': {'en': 'Mozambique', 'zh_sim': '莫桑比克', 'zh_tra': '莫桑比克'}},
 {'key': 'MM', 'cr': 'countryMM', 'code': 'MM', 'labels': {'en': 'Myanmar', 'zh_sim': '缅甸', 'zh_tra': '緬甸'}},
 {'key': 'NA', 'cr': 'countryNA', 'code': 'NA', 'labels': {'en': 'Namibia', 'zh_sim': '纳米比亚', 'zh_tra': '納米比亞'}},
 {'key': 'NR', 'cr': 'countryNR', 'code': 'NR', 'labels': {'en': 'Nauru', 'zh_sim': '瑙鲁', 'zh_tra': '瑙魯'}},
 {'key': 'NP', 'cr': 'countryNP', 'code': 'NP', 'labels': {'en': 'Nepal', 'zh_sim': '尼泊尔', 'zh_tra': '尼泊爾'}},
 {'key': 'NL', 'cr': 'countryNL', 'code': 'NL', 'labels': {'en': 'Netherlands', 'zh_sim': '荷兰', 'zh_tra': '荷蘭'}},
 {'key': 'AN',
  'cr': 'countryAN',
  'code': 'AN',
  'labels': {'en': 'Netherlands Antilles', 'zh_sim': '荷属安的列斯', 'zh_tra': '荷属安的列斯'}},
 {'key': 'NC',
  'cr': 'countryNC',
  'code': 'NC',
  'labels': {'en': 'New Caledonia', 'zh_sim': '新喀里多尼亚', 'zh_tra': '新喀里多尼亞'}},
 {'key': 'NZ', 'cr': 'countryNZ', 'code': 'NZ', 'labels': {'en': 'New Zealand', 'zh_sim': '新西兰', 'zh_tra': '新西蘭'}},
 {'key': 'NI', 'cr': 'countryNI', 'code': 'NI', 'labels': {'en': 'Nicaragua', 'zh_sim': '尼加拉瓜', 'zh_tra': '尼加拉瓜'}},
 {'key': 'NE', 'cr': 'countryNE', 'code': 'NE', 'labels': {'en': 'Niger', 'zh_sim': '尼日尔', 'zh_tra': '尼日爾'}},
 {'key': 'NG', 'cr': 'countryNG', 'code': 'NG', 'labels': {'en': 'Nigeria', 'zh_sim': '尼日利亚', 'zh_tra': '尼日利亞'}},
 {'key': 'NU', 'cr': 'countryNU', 'code': 'NU', 'labels': {'en': 'Niue', 'zh_sim': '纽埃', 'zh_tra': '纽埃'}},
 {'key': 'NF', 'cr': 'countryNF', 'code': 'NF', 'labels': {'en': 'Norfolk Island', 'zh_sim': '诺福克岛', 'zh_tra': '诺福克島'}},
 {'key': 'MP',
  'cr': 'countryMP',
  'code': 'MP',
  'labels': {'en': 'Northern Mariana Islands', 'zh_sim': '北马里亚纳群岛', 'zh_tra': '北馬里亞納群島'}},
 {'key': 'NO', 'cr': 'countryNO', 'code': 'NO', 'labels': {'en': 'Norway', 'zh_sim': '挪威', 'zh_tra': '挪威'}},
 {'key': 'OM', 'cr': 'countryOM', 'code': 'OM', 'labels': {'en': 'Oman', 'zh_sim': '阿曼', 'zh_tra': '阿曼'}},
 {'key': 'PK', 'cr': 'countryPK', 'code': 'PK', 'labels': {'en': 'Pakistan', 'zh_sim': '巴基斯坦', 'zh_tra': '巴基斯坦'}},
 {'key': 'PW', 'cr': 'countryPW', 'code': 'PW', 'labels': {'en': 'Palau', 'zh_sim': '帕劳', 'zh_tra': '帕劳'}},
 {'key': 'PS',
  'cr': 'countryPS',
  'code': 'PS',
  'labels': {'en': 'Palestinian Territories', 'zh_sim': '巴勒斯坦地区', 'zh_tra': '巴勒斯坦地區'}},
 {'key': 'PA', 'cr': 'countryPA', 'code': 'PA', 'labels': {'en': 'Panama', 'zh_sim': '巴拿马', 'zh_tra': '巴拿馬'}},
 {'key': 'PG',
  'cr': 'countryPG',
  'code': 'PG',
  'labels': {'en': 'Papua New Guinea', 'zh_sim': '巴布亚新几内亚', 'zh_tra': '巴布亞新几内亞'}},
 {'key': 'PY', 'cr': 'countryPY', 'code': 'PY', 'labels': {'en': 'Paraguay', 'zh_sim': '巴拉圭', 'zh_tra': '巴拉圭'}},
 {'key': 'PE', 'cr': 'countryPE', 'code': 'PE', 'labels': {'en': 'Peru', 'zh_sim': '秘鲁', 'zh_tra': '秘魯'}},
 {'key': 'PH', 'cr': 'countryPH', 'code': 'PH', 'labels': {'en': 'Philippines', 'zh_sim': '菲律宾', 'zh_tra': '菲律賓'}},
 {'key': 'PN', 'cr': 'countryPN', 'code': 'PN', 'labels': {'en': 'Pitcairn', 'zh_sim': '皮特凯恩', 'zh_tra': '皮特凯恩'}},
 {'key': 'PL', 'cr': 'countryPL', 'code': 'PL', 'labels': {'en': 'Poland', 'zh_sim': '波兰', 'zh_tra': '波蘭'}},
 {'key': 'PT', 'cr': 'countryPT', 'code': 'PT', 'labels': {'en': 'Portugal', 'zh_sim': '葡萄牙', 'zh_tra': '葡萄牙'}},
 {'key': 'PR', 'cr': 'countryPR', 'code': 'PR', 'labels': {'en': 'Puerto Rico', 'zh_sim': '波多黎各', 'zh_tra': '波多黎各'}},
 {'key': 'QA', 'cr': 'countryQA', 'code': 'QA', 'labels': {'en': 'Qatar', 'zh_sim': '卡塔尔', 'zh_tra': '卡塔爾'}},
 {'key': 'RE', 'cr': 'countryRE', 'code': 'RE', 'labels': {'en': 'Réunion', 'zh_sim': '留尼旺', 'zh_tra': '留尼旺'}},
 {'key': 'RO', 'cr': 'countryRO', 'code': 'RO', 'labels': {'en': 'Romania', 'zh_sim': '罗马尼亚', 'zh_tra': '羅馬尼亞'}},
 {'key': 'RU', 'cr': 'countryRU', 'code': 'RU', 'labels': {'en': 'Russia', 'zh_sim': '俄罗斯联邦', 'zh_tra': '俄羅斯聯邦'}},
 {'key': 'RW', 'cr': 'countryRW', 'code': 'RW', 'labels': {'en': 'Rwanda', 'zh_sim': '卢旺达', 'zh_tra': '盧旺達'}},
 {'key': 'SH',
  'cr': 'countrySH',
  'code': 'SH',
  'labels': {'en': 'Saint Helena, Ascension and Tristan da Cunha', 'zh_sim': '圣赫勒拿', 'zh_tra': '聖赫勒拿'}},
 {'key': 'KN',
  'cr': 'countryKN',
  'code': 'KN',
  'labels': {'en': 'Saint Kitts and Nevis', 'zh_sim': '圣基茨和尼维斯', 'zh_tra': '聖基茨和尼維斯'}},
 {'key': 'LC', 'cr': 'countryLC', 'code': 'LC', 'labels': {'en': 'Saint Lucia', 'zh_sim': '圣卢西亚', 'zh_tra': '聖盧西亞'}},
 {'key': 'PM',
  'cr': 'countryPM',
  'code': 'PM',
  'labels': {'en': 'Saint Pierre and Miquelon', 'zh_sim': '圣皮埃尔和密克隆', 'zh_tra': '聖皮埃爾和密克隆'}},
 {'key': 'VC',
  'cr': 'countryVC',
  'code': 'VC',
  'labels': {'en': 'Saint Vincent and the Grenadines', 'zh_sim': '圣文森特和格林纳丁斯', 'zh_tra': '聖文森特和格林納丁斯'}},
 {'key': 'WS', 'cr': 'countryWS', 'code': 'WS', 'labels': {'en': 'Samoa', 'zh_sim': '萨摩亚', 'zh_tra': '薩摩亞'}},
 {'key': 'SM', 'cr': 'countrySM', 'code': 'SM', 'labels': {'en': 'San Marino', 'zh_sim': '圣马力诺', 'zh_tra': '聖馬力诺'}},
 {'key': 'ST',
  'cr': 'countryST',
  'code': 'ST',
  'labels': {'en': 'Sao Tome and Principe', 'zh_sim': '圣多美和普林西比', 'zh_tra': '聖多美和普林西比'}},
 {'key': 'SA', 'cr': 'countrySA', 'code': 'SA', 'labels': {'en': 'Saudi Arabia', 'zh_sim': '沙特阿拉伯', 'zh_tra': '沙特阿拉伯'}},
 {'key': 'SN', 'cr': 'countrySN', 'code': 'SN', 'labels': {'en': 'Senegal', 'zh_sim': '塞内加尔', 'zh_tra': '塞内加爾'}},
 {'key': 'CS',
  'cr': 'countryCS',
  'code': 'CS',
  'labels': {'en': 'Serbia and Montenegro', 'zh_sim': '塞尔维亚和黑山', 'zh_tra': '塞爾維亞和黑山'}},
 {'key': 'SC', 'cr': 'countrySC', 'code': 'SC', 'labels': {'en': 'Seychelles', 'zh_sim': '塞舌尔', 'zh_tra': '塞舌爾'}},
 {'key': 'SL', 'cr': 'countrySL', 'code': 'SL', 'labels': {'en': 'Sierra Leone', 'zh_sim': '塞拉利昂', 'zh_tra': '塞拉利昂'}},
 {'key': 'SG', 'cr': 'countrySG', 'code': 'SG', 'labels': {'en': 'Singapore', 'zh_sim': '新加坡', 'zh_tra': '新加坡'}},
 {'key': 'SK', 'cr': 'countrySK', 'code': 'SK', 'labels': {'en': 'Slovakia', 'zh_sim': '斯洛伐克', 'zh_tra': '斯洛伐克'}},
 {'key': 'SI', 'cr': 'countrySI', 'code': 'SI', 'labels': {'en': 'Slovenia', 'zh_sim': '斯洛文尼亚', 'zh_tra': '斯洛文尼亞'}},
 {'key': 'SB',
  'cr': 'countrySB',
  'code': 'SB',
  'labels': {'en': 'Solomon Islands', 'zh_sim': '所罗门群岛', 'zh_tra': '所羅門群島'}},
 {'key': 'SO', 'cr': 'countrySO', 'code': 'SO', 'labels': {'en': 'Somalia', 'zh_sim': '索马里', 'zh_tra': '索馬里'}},
 {'key': 'ZA', 'cr': 'countryZA', 'code': 'ZA', 'labels': {'en': 'South Africa', 'zh_sim': '南非', 'zh_tra': '南非'}},
 {'key': 'GS',
  'cr': 'countryGS',
  'code': 'GS',
  'labels': {'en': 'South Georgia and the South Sandwich Islands', 'zh_sim': '南乔治亚和南桑威奇群岛', 'zh_tra': '南喬治亞和南桑威奇群島'}},
 {'key': 'ES', 'cr': 'countryES', 'code': 'ES', 'labels': {'en': 'Spain', 'zh_sim': '西班牙', 'zh_tra': '西班牙'}},
 {'key': 'LK', 'cr': 'countryLK', 'code': 'LK', 'labels': {'en': 'Sri Lanka', 'zh_sim': '斯里兰卡', 'zh_tra': '斯里蘭卡'}},
 {'key': 'SD', 'cr': 'countrySD', 'code': 'SD', 'labels': {'en': 'Sudan', 'zh_sim': '苏丹', 'zh_tra': '蘇丹'}},
 {'key': 'SR', 'cr': 'countrySR', 'code': 'SR', 'labels': {'en': 'Suriname', 'zh_sim': '苏里南', 'zh_tra': '蘇里南'}},
 {'key': 'SJ',
  'cr': 'countrySJ',
  'code': 'SJ',
  'labels': {'en': 'Svalbard and Jan Mayen', 'zh_sim': '斯瓦尔巴和扬马延', 'zh_tra': '斯瓦爾巴和扬馬延'}},
 {'key': 'SZ', 'cr': 'countrySZ', 'code': 'SZ', 'labels': {'en': 'Eswatini', 'zh_sim': '斯威士兰', 'zh_tra': '斯威士蘭'}},
 {'key': 'SE', 'cr': 'countrySE', 'code': 'SE', 'labels': {'en': 'Sweden', 'zh_sim': '瑞典', 'zh_tra': '瑞典'}},
 {'key': 'CH', 'cr': 'countryCH', 'code': 'CH', 'labels': {'en': 'Switzerland', 'zh_sim': '瑞士', 'zh_tra': '瑞士'}},
 {'key': 'SY',
  'cr': 'countrySY',
  'code': 'SY',
  'labels': {'en': 'Syria', 'zh_sim': '阿拉伯叙利亚共和国', 'zh_tra': '阿拉伯叙利亞共和國'}},
 {'key': 'TW',
  'cr': 'countryTW',
  'code': 'TW',
  'labels': {'en': 'China Taiwan Province', 'zh_sim': '中国台湾省', 'zh_tra': '中國臺灣省'}},
 {'key': 'TJ', 'cr': 'countryTJ', 'code': 'TJ', 'labels': {'en': 'Tajikistan', 'zh_sim': '塔吉克斯坦', 'zh_tra': '塔吉克斯坦'}},
 {'key': 'TZ',
  'cr': 'countryTZ',
  'code': 'TZ',
  'labels': {'en': 'Tanzania', 'zh_sim': '坦桑尼亚联合共和国', 'zh_tra': '坦桑尼亞聯合共和國'}},
 {'key': 'TH', 'cr': 'countryTH', 'code': 'TH', 'labels': {'en': 'Thailand', 'zh_sim': '泰国', 'zh_tra': '泰國'}},
 {'key': 'TG', 'cr': 'countryTG', 'code': 'TG', 'labels': {'en': 'Togo', 'zh_sim': '多哥', 'zh_tra': '多哥'}},
 {'key': 'TK', 'cr': 'countryTK', 'code': 'TK', 'labels': {'en': 'Tokelau', 'zh_sim': '托克劳', 'zh_tra': '托克劳'}},
 {'key': 'TO', 'cr': 'countryTO', 'code': 'TO', 'labels': {'en': 'Tonga', 'zh_sim': '汤加', 'zh_tra': '汤加'}},
 {'key': 'TT',
  'cr': 'countryTT',
  'code': 'TT',
  'labels': {'en': 'Trinidad and Tobago', 'zh_sim': '特立尼达和多巴哥', 'zh_tra': '特立尼達和多巴哥'}},
 {'key': 'TN', 'cr': 'countryTN', 'code': 'TN', 'labels': {'en': 'Tunisia', 'zh_sim': '突尼斯', 'zh_tra': '突尼斯'}},
 {'key': 'TR', 'cr': 'countryTR', 'code': 'TR', 'labels': {'en': 'Türkiye', 'zh_sim': '土耳其', 'zh_tra': '土耳其'}},
 {'key': 'TM', 'cr': 'countryTM', 'code': 'TM', 'labels': {'en': 'Turkmenistan', 'zh_sim': '土库曼斯坦', 'zh_tra': '土庫曼斯坦'}},
 {'key': 'TC',
  'cr': 'countryTC',
  'code': 'TC',
  'labels': {'en': 'Turks and Caicos Islands', 'zh_sim': '特克斯和凯科斯群岛', 'zh_tra': '特克斯和凯科斯群島'}},
 {'key': 'TV', 'cr': 'countryTV', 'code': 'TV', 'labels': {'en': 'Tuvalu', 'zh_sim': '图瓦卢', 'zh_tra': '图瓦盧'}},
 {'key': 'UG', 'cr': 'countryUG', 'code': 'UG', 'labels': {'en': 'Uganda', 'zh_sim': '乌干达', 'zh_tra': '烏干達'}},
 {'key': 'UA', 'cr': 'countryUA', 'code': 'UA', 'labels': {'en': 'Ukraine', 'zh_sim': '乌克兰', 'zh_tra': '烏克蘭'}},
 {'key': 'AE',
  'cr': 'countryAE',
  'code': 'AE',
  'labels': {'en': 'United Arab Emirates', 'zh_sim': '阿拉伯联合酋长国', 'zh_tra': '阿拉伯聯合酋长國'}},
 {'key': 'UK', 'cr': 'countryUK', 'code': 'UK', 'labels': {'en': 'United Kingdom', 'zh_sim': '英国', 'zh_tra': '英國'}},
 {'key': 'US', 'cr': 'countryUS', 'code': 'US', 'labels': {'en': 'United States', 'zh_sim': '美国', 'zh_tra': '美國'}},
 {'key': 'UM',
  'cr': 'countryUM',
  'code': 'UM',
  'labels': {'en': 'United States Minor Outlying Islands', 'zh_sim': '美国本土外小岛屿', 'zh_tra': '美國本土外小島屿'}},
 {'key': 'UY', 'cr': 'countryUY', 'code': 'UY', 'labels': {'en': 'Uruguay', 'zh_sim': '乌拉圭', 'zh_tra': '烏拉圭'}},
 {'key': 'UZ', 'cr': 'countryUZ', 'code': 'UZ', 'labels': {'en': 'Uzbekistan', 'zh_sim': '乌兹别克斯坦', 'zh_tra': '烏兹别克斯坦'}},
 {'key': 'VU', 'cr': 'countryVU', 'code': 'VU', 'labels': {'en': 'Vanuatu', 'zh_sim': '瓦努阿图', 'zh_tra': '瓦努阿图'}},
 {'key': 'VE',
  'cr': 'countryVE',
  'code': 'VE',
  'labels': {'en': 'Venezuela, Bolivarian Republic of', 'zh_sim': '委内瑞拉', 'zh_tra': '委内瑞拉'}},
 {'key': 'VN', 'cr': 'countryVN', 'code': 'VN', 'labels': {'en': 'Viet Nam', 'zh_sim': '越南', 'zh_tra': '越南'}},
 {'key': 'VG',
  'cr': 'countryVG',
  'code': 'VG',
  'labels': {'en': 'Virgin Islands, British', 'zh_sim': '英属维尔京群岛', 'zh_tra': '英属維爾京群島'}},
 {'key': 'VI',
  'cr': 'countryVI',
  'code': 'VI',
  'labels': {'en': 'Virgin Islands, U.S.', 'zh_sim': '美属维尔京群岛', 'zh_tra': '美属維爾京群島'}},
 {'key': 'WF',
  'cr': 'countryWF',
  'code': 'WF',
  'labels': {'en': 'Wallis and Futuna', 'zh_sim': '瓦利斯和福图纳', 'zh_tra': '瓦利斯和福图納'}},
 {'key': 'EH', 'cr': 'countryEH', 'code': 'EH', 'labels': {'en': 'Western Sahara', 'zh_sim': '西撒哈拉', 'zh_tra': '西撒哈拉'}},
 {'key': 'YE', 'cr': 'countryYE', 'code': 'YE', 'labels': {'en': 'Yemen', 'zh_sim': '也门', 'zh_tra': '也門'}},
 {'key': 'YU', 'cr': 'countryYU', 'code': 'YU', 'labels': {'en': 'Yugoslavia', 'zh_sim': '南斯拉夫', 'zh_tra': '南斯拉夫'}},
 {'key': 'ZM', 'cr': 'countryZM', 'code': 'ZM', 'labels': {'en': 'Zambia', 'zh_sim': '赞比亚', 'zh_tra': '赞比亞'}},
 {'key': 'ZW', 'cr': 'countryZW', 'code': 'ZW', 'labels': {'en': 'Zimbabwe', 'zh_sim': '津巴布韦', 'zh_tra': '津巴布韦'}}]

OUTPUT_FORMATS = ['xlsx', 'csv', 'txt', 'docx', 'xml']

CONTENT_CLEANING_OPTIONS = [{'key': 'auto', 'labels': {'en': 'Auto by source/domain', 'zh_sim': '自动按来源/域名选择', 'zh_tra': '自動按來源/網域選擇'}},
 {'key': 'newspaper_news',
  'labels': {'en': 'News: newspaper3k first', 'zh_sim': '新闻：优先 newspaper3k', 'zh_tra': '新聞：優先 newspaper3k'}},
 {'key': 'news_article',
  'labels': {'en': 'News article: article/main', 'zh_sim': '新闻正文：article/main', 'zh_tra': '新聞正文：article/main'}},
 {'key': 'general_web', 'labels': {'en': 'General webpage', 'zh_sim': '通用网页', 'zh_tra': '通用網頁'}},
 {'key': 'light_archive',
  'labels': {'en': 'Light archive / academic', 'zh_sim': '轻度清洁：归档/学术页', 'zh_tra': '輕度清潔：歸檔/學術頁'}},
 {'key': 'strict_corpus', 'labels': {'en': 'Strict corpus clean', 'zh_sim': '严格语料清洁', 'zh_tra': '嚴格語料清潔'}}]

QUERY_MODE_OPTIONS = [{'key': 'single', 'labels': {'en': 'Single term', 'zh_sim': '单个检索词', 'zh_tra': '單個檢索詞'}},
 {'key': 'any', 'labels': {'en': 'Any term, OR', 'zh_sim': '多个检索词：OR', 'zh_tra': '多個檢索詞：OR'}},
 {'key': 'all', 'labels': {'en': 'All terms', 'zh_sim': '多个检索词：全部包含', 'zh_tra': '多個檢索詞：全部包含'}},
 {'key': 'phrase', 'labels': {'en': 'Exact phrase', 'zh_sim': '严格连续短语', 'zh_tra': '嚴格連續短語'}},
 {'key': 'phrase_any', 'labels': {'en': 'Any exact phrase, OR', 'zh_sim': '多个严格短语：OR', 'zh_tra': '多個嚴格短語：OR'}},
 {'key': 'raw', 'labels': {'en': 'Raw search query', 'zh_sim': '原始检索式', 'zh_tra': '原始檢索式'}}]

VERTICAL_OPTIONS = [
 {'key': 'news', 'labels': {'en': 'Google News tab', 'zh_sim': 'Google 新闻标签', 'zh_tra': 'Google 新聞標籤'}},
 {'key': 'web', 'labels': {'en': 'Google Web search', 'zh_sim': 'Google 网页检索', 'zh_tra': 'Google 網頁檢索'}},
 {'key': 'baidu_web', 'labels': {'en': 'Baidu Web search', 'zh_sim': '百度网页检索', 'zh_tra': '百度網頁檢索'}},
 {'key': 'baidu_news', 'labels': {'en': 'Baidu News / Information', 'zh_sim': '百度资讯', 'zh_tra': '百度資訊'}},
 {'key': 'baidu_news_media', 'labels': {'en': 'Baidu News - media sites', 'zh_sim': '百度资讯：媒体网站', 'zh_tra': '百度資訊：媒體網站'}},
]
BAIDU_SORT_OPTIONS = [
 {'key': 'focus', 'labels': {'en': 'Baidu focus / relevance sort', 'zh_sim': '百度按焦点/相关排序', 'zh_tra': '百度按焦點/相關排序'}},
 {'key': 'time', 'labels': {'en': 'Baidu time sort', 'zh_sim': '百度按时间排序', 'zh_tra': '百度按時間排序'}},
]

FETCH_BACKEND_OPTIONS = [{'key': 'selenium_chrome',
  'labels': {'en': 'Selenium Chrome browser (recommended)',
             'zh_sim': 'Selenium Chrome 浏览器模式（推荐）',
             'zh_tra': 'Selenium Chrome 瀏覽器模式（推薦）'}},
 {'key': 'selenium_edge',
  'labels': {'en': 'Selenium Edge browser', 'zh_sim': 'Selenium Edge 浏览器模式', 'zh_tra': 'Selenium Edge 瀏覽器模式'}},
 {'key': 'requests',
  'labels': {'en': 'Requests HTTP mode (lightweight)',
             'zh_sim': 'Requests HTTP 模式（轻量）',
             'zh_tra': 'Requests HTTP 模式（輕量）'}}]

CONTENT_FETCH_MODE_OPTIONS = [
 {'key': 'mixed',
  'labels': {'en': 'Requests first + Selenium fallback',
             'zh_sim': 'Requests 优先 + Selenium 兜底',
             'zh_tra': 'Requests 優先 + Selenium 備援'}},
 {'key': 'requests',
  'labels': {'en': 'Requests only',
             'zh_sim': '仅 Requests 下载',
             'zh_tra': '僅 Requests 下載'}},
 {'key': 'selenium',
  'labels': {'en': 'Selenium browser only',
             'zh_sim': '仅 Selenium 浏览器下载',
             'zh_tra': '僅 Selenium 瀏覽器下載'}},
]


def label_for(option: dict, lang: str, include_value: bool = False, value_key: str | None = None) -> str:
    """Return a user-facing label.

    ``include_value`` and ``value_key`` are kept for backward compatibility with
    older callers, but release UI labels deliberately do not append technical
    values such as [lang_en] or [countryUS].
    """
    return option.get("labels", {}).get(lang) or option.get("labels", {}).get("en") or option.get("key", "")


def labels_for(options: list[dict], lang: str, include_value: bool = False, value_key: str | None = None) -> list[str]:
    return [label_for(opt, lang, include_value, value_key) for opt in options]


def option_by_key(options: list[dict], key: str) -> dict | None:
    for opt in options:
        if opt.get("key") == key:
            return opt
    return None


def _strip_legacy_value_suffix(label: str) -> str:
    """Accept old labels like 'English [lang_en]' when switching UI language."""
    if not label:
        return ""
    label = label.strip()
    if label.endswith("]") and " [" in label:
        return label.rsplit(" [", 1)[0].strip()
    return label


def option_by_label(options: list[dict], label: str, lang: str, value_key: str | None = None) -> dict | None:
    normalized_label = _strip_legacy_value_suffix(label)
    for opt in options:
        current = label_for(opt, lang)
        english = label_for(opt, "en")
        if current == normalized_label or english == normalized_label:
            return opt
        # Backward-compatible matching for older visible labels with technical values.
        if value_key and opt.get(value_key):
            old_current = f"{current} [{opt[value_key]}]"
            old_english = f"{english} [{opt[value_key]}]"
            if label == old_current or label == old_english:
                return opt
    return None
